/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.0
 *
 * Project: 'object-detection.Release-Live_Stream+AE722F80F55D5LS-U55-256' 
 * Target:  'Release-Live_Stream+AE722F80F55D5LS-U55-256' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.26.2 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55
/* tensorflow::Machine Learning:TensorFlow:Kernel&Ethos-U@1.26.2 */
// enabling global pre includes 
        #define TF_LITE_STATIC_MEMORY 1
        #define TF_LITE_DISABLE_X86_NEON 1
        //#define TF_LITE_STRIP_ERROR_STRINGS 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */
