/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.14.1+p78-g96628360
 *
 * Project: 'kws.Debug-Live_Stream+AVH-SSE-300'
 * Target:  'Debug-Live_Stream+AVH-SSE-300'
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* ARM::Machine Learning:MLEK:FwkImpl&TensorFlowLiteMicro@2.0.0 */
#define MLEK_LOG_ENABLE
#define MLEK_LOG_LEVEL MLEK_LOG_LEVEL_INFO
/* ARM::Machine Learning:MLEK:Math@2.0.0 */
#define MLEK_LOG_ENABLE
#define MLEK_LOG_LEVEL MLEK_LOG_LEVEL_INFO
/* tensorflow::Machine Learning:TensorFlow:Kernel&CMSIS-NN@1.26.5 */
// enabling global pre includes
        #define TF_LITE_STATIC_MEMORY 1
        #define CMSIS_NN


#endif /* PRE_INCLUDE_GLOBAL_H */